-- ============================================================================
--  100 additional sample phrases for the reading dataset.
--  Original, made-up one-sentence prompts (sort continues from 7).
--  Dollar-quoted so apostrophes need no escaping.
-- ============================================================================

insert into public.sample_phrases (text, sort) values
($$The morning fog rolled gently across the quiet valley.$$, 7),
($$We should plant tomatoes along the south fence this spring.$$, 8),
($$Her laughter echoed through the empty concert hall.$$, 9),
($$Please remember to water the ferns while I am away.$$, 10),
($$A gentle breeze carried the scent of fresh lavender.$$, 11),
($$They danced until the band packed up their instruments.$$, 12),
($$The old lighthouse still guards the rocky northern coast.$$, 13),
($$I cannot believe how quickly the summer has passed.$$, 14),
($$My grandmother bakes the most wonderful cinnamon bread.$$, 15),
($$The children built an enormous sandcastle near the tide.$$, 16),
($$Could you turn down the music just a little, please?$$, 17),
($$Bright yellow daffodils lined the path to the cottage.$$, 18),
($$He whispered the secret so softly I almost missed it.$$, 19),
($$The thunderstorm knocked out power across the whole town.$$, 20),
($$She painted the bedroom a calming shade of seafoam green.$$, 21),
($$Our train departs at a quarter past seven tomorrow.$$, 22),
($$The puppy chased its tail in dizzy little circles.$$, 23),
($$Warm sunlight spilled across the kitchen table at dawn.$$, 24),
($$I would love a cup of tea with a touch of honey.$$, 25),
($$The river sparkled beneath the bright afternoon sky.$$, 26),
($$They hiked for hours before reaching the misty summit.$$, 27),
($$A single candle flickered on the windowsill all night.$$, 28),
($$The market sells fresh peaches every Saturday morning.$$, 29),
($$We watched the fireworks burst above the calm harbor.$$, 30),
($$His voice grew steadier as the speech went on.$$, 31),
($$The librarian recommended a thrilling mystery novel.$$, 32),
($$Snowflakes settled quietly on the sleeping garden.$$, 33),
($$She tied a bright ribbon around the birthday gift.$$, 34),
($$The chef sprinkled basil over the steaming pasta.$$, 35),
($$Our neighbors invited us for dinner on Friday evening.$$, 36),
($$The kitten curled up beside the crackling fireplace.$$, 37),
($$I forgot my umbrella, so I waited under the awning.$$, 38),
($$The mountains glowed pink as the sun slipped away.$$, 39),
($$He carefully folded the letter and sealed the envelope.$$, 40),
($$A flock of geese flew south in a perfect arrow.$$, 41),
($$The bakery smelled of warm bread and roasted coffee.$$, 42),
($$She hummed a cheerful tune while washing the dishes.$$, 43),
($$The lake was so still it mirrored the entire sky.$$, 44),
($$We need to leave early to beat the holiday traffic.$$, 45),
($$The orchestra tuned their strings before the performance.$$, 46),
($$Fresh rain made the city streets glisten under the lamps.$$, 47),
($$My brother collects stamps from faraway countries.$$, 48),
($$The gardener trimmed the roses into neat little hedges.$$, 49),
($$A curious fox peeked out from behind the woodpile.$$, 50),
($$They roasted marshmallows over the glowing campfire.$$, 51),
($$The teacher explained the lesson with great patience.$$, 52),
($$I love the smell of pine trees after a light snow.$$, 53),
($$She sketched the harbor while the boats drifted by.$$, 54),
($$The bell rang twice before the meeting finally began.$$, 55),
($$Wildflowers covered the hillside in every color imaginable.$$, 56),
($$He balanced the heavy boxes all the way up the stairs.$$, 57),
($$The ocean waves crashed rhythmically against the pier.$$, 58),
($$We shared a slice of warm apple pie after lunch.$$, 59),
($$The actor delivered each line with quiet confidence.$$, 60),
($$A rainbow stretched across the sky after the storm.$$, 61),
($$She wrapped the scarf twice around her chilly neck.$$, 62),
($$The old clock chimed softly in the dusty hallway.$$, 63),
($$Birds sang loudly outside my window this morning.$$, 64),
($$They paddled the canoe across the glassy green lake.$$, 65),
($$The smell of cinnamon filled the cozy little kitchen.$$, 66),
($$I planted three rows of carrots behind the shed.$$, 67),
($$The dancer spun gracefully beneath the golden lights.$$, 68),
($$We strolled along the boardwalk as the sun set.$$, 69),
($$His handwriting was neat enough to read from across the room.$$, 70),
($$The garden buzzed with bees on that warm afternoon.$$, 71),
($$She carefully arranged the tulips in a glass vase.$$, 72),
($$The campers told ghost stories long into the night.$$, 73),
($$A soft melody drifted from the open cafe door.$$, 74),
($$The farmer loaded the wagon with bright orange pumpkins.$$, 75),
($$I finally finished the puzzle after three long evenings.$$, 76),
($$The waves left tiny shells scattered across the sand.$$, 77),
($$He whistled cheerfully as he swept the front porch.$$, 78),
($$The autumn leaves crunched beneath our morning walk.$$, 79),
($$She poured the lemonade into tall frosted glasses.$$, 80),
($$The kite soared higher with every gust of wind.$$, 81),
($$We counted the stars until our eyes grew heavy.$$, 82),
($$The baker dusted the muffins with powdered sugar.$$, 83),
($$A warm blanket and a good book made the evening perfect.$$, 84),
($$The mechanic fixed the engine in under an hour.$$, 85),
($$Bright lanterns lit the path through the festival.$$, 86),
($$She read the bedtime story in a gentle, soothing voice.$$, 87),
($$The train rumbled past the fields of golden wheat.$$, 88),
($$I spotted a deer grazing quietly near the creek.$$, 89),
($$The choir filled the chapel with a beautiful harmony.$$, 90),
($$We picked ripe strawberries until our baskets overflowed.$$, 91),
($$The painter mixed a vivid shade of sunset orange.$$, 92),
($$A cool mist hung over the meadow at first light.$$, 93),
($$He tuned the guitar and began to play softly.$$, 94),
($$The shop window displayed rows of colorful candies.$$, 95),
($$She laughed so hard that tears rolled down her cheeks.$$, 96),
($$The sailboat glided smoothly across the open bay.$$, 97),
($$We roasted chestnuts on the stove during the snowfall.$$, 98),
($$The toddler giggled at the bouncing red balloon.$$, 99),
($$A gentle rain tapped against the windowpane all afternoon.$$, 100),
($$The hikers paused to admire the sweeping valley below.$$, 101),
($$She wrote her name carefully at the top of the page.$$, 102),
($$The crowd cheered as the runners crossed the finish line.$$, 103),
($$Warm bread and butter is my favorite simple meal.$$, 104),
($$The moon rose slowly above the silent rooftops.$$, 105),
($$We waved goodbye until the car disappeared around the bend.$$, 106);
